# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b47ac3e57b127adfa89c874551f8cea1ff05d214bbacb76d4cc87742202967316abbb5b4c40f16fbff850129f621c30ccd300b5e07452e6c754dba141453e95f

test:
  secret_key_base: 39f964b26c36faaf9e7c533e655084bcb9196c646aa8b5047896dc1a83063e98cf2ba176c96e8229b918054d1ee4f990c4427e15b2940014571c0fec30a5b161

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
